$ANSIBLE_VAULT;1.1;AES256
30616365616330366362373931316166396664626539353133363331646237653633316466643863
6535303635303430623636666161663866666337356264380a613965336263323361396530336162
35626362646238663735373035633935663133636237373562366666366435353133373064666431
6237353264633332620a373136356131626261386530313265313962303261323733616332393639
64383834656462343435373839393535666437313661333137313236363637633539343635323532
3865366564306164626135666562623038666164343632333536