- name: Ensure nginx 1.24 module stream is enabled
  ansible.builtin.dnf:
    name: '@nginx:1.24'
    state: present

- name: Install Nginx using DNF
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Remove the entire directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create directory again html
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download the frontend content
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip


- name: Unzip the downloaded file
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Remove default Nginx config file
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: Deploy Nginx configuration file from template
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx




